### ISSUE TITLE
Automated monitoring of autoreduction service

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#109]
This issue was originally [TRAC 11322](http://trac.mantidproject.org/mantid/ticket/11322)

Get autoreduction service setup with the computing group nagios so that email notification are send out if a service goes down 

 - - - - 
Keywords: AUTOREDUCTION

**Comment by Anders-Markvardsen** [comment]
@DominicOram when it has been setup, please specify a step by step instructions for how we can test that it has been setup.

**Comment by DominicOram** [comment]
This has now been setup. To test: 
* Go to https://varanus.nd.rl.ac.uk/nagios/ and log in with your fedID (currently works for @Anders-Markvardsen and @lottiegreenwood). 
* Under the hosts section on the left you should see both the autoreduce and reduce servers. Here it will be shown if the servers are Up/Down.
* Under the services section you should see a service named WEB on the reduce server, which will show whether the website is Up/Down.
* Stop the website through the IIS Manager on the reduce server
* Click on the WEB service and click re-schedule, then commit
* Wait until the next scheduled check time, the status should now show critical
* Repeat the last two steps 3 times and confirm that an email is sent to ISISREDUCE@stfc.ac.uk

**Comment by Anders-Markvardsen** [comment]
That this service works has been verified
