### ISSUE TITLE
User should have ability to rerun their old runs

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#112]
This issue was originally [TRAC 11357](http://trac.mantidproject.org/mantid/ticket/11357)

Currently only runs that have been run through autoreduce already, whether from a lookup script or an instrument, can be rerun. Users would like the ability to run their old runs regardless of whether they have already been through the autoreduction website

---

Keywords: AUTOREDUCTION

**Comment by DominicOram** [comment]
This feature will most likely be included as part of #81

**Comment by tg137** [comment]
This is already implemented.
