### ISSUE TITLE
Ability to rerun multiple jobs

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#113]
This issue was originally [TRAC 11358](http://trac.mantidproject.org/mantid/ticket/11358)

Currently in autoreduction, jobs can be rerun only one at a time. Users would like to be able to rerun jobs in batches for convenience.

 - - - - 
Keywords: AUTOREDUCTION

**Comment by Anders-Markvardsen** [comment]
This is a dublicate of #81
