### ISSUE TITLE
Backup WebApp database

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#120]
This issue was originally [TRAC 11385](http://trac.mantidproject.org/mantid/ticket/11385)

Currently backed up as part of the Window server VM backup, but if the database itself becomes corrupt then we lose data.

Marcus suggested we could e.g. periodically dump out mysql files for backup. 

This ticket is to back up the database in e.g. this way

---

Keywords: AUTOREDUCTION

**Comment by tg137** [comment]
I have scheduled this backup to run once daily on the reduce server. Each backup will be kept for 7 days before being deleted. The task is scheduled from the Windows Task Scheduler and will be run at 23:00 each day.
