### ISSUE TITLE
Add browse button to reduce variable forms

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#121]
This issue was originally [TRAC 11396](http://trac.mantidproject.org/mantid/ticket/11396)

Currently the only way to use a file is if it is already contained with instrument files and you already know the exact name of it. If a browse button was added to the form, this would increase usability.

---

Keywords: AUTOREDUCTION

**Comment by Anders-Markvardsen** [comment]
@lottiegreenwood could you add a step by step instructions of how a user benefit from an added browse button

**Comment by lottiegreenwood** [comment]
For some reduction scripts, other .raw files are used (eg. for LET, wb_run needs to be selected). Currently the user needs to type the file name into the re-run form manually, and so long as the run is contained within the instrument files folder, it will be used. It would be more user friendly to include a browse button so users can just select a run, ideally both inside and outside of the instrument files folder.

**Comment by lottiegreenwood** [comment]
Currently not required
