### ISSUE TITLE
Reduce_vars.py interface should allow non-entry of information

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#122]
This issue was originally [TRAC 11401](http://trac.mantidproject.org/mantid/ticket/11401)

Currently, even if the default in the reduce_vars.py script is an empty string, if entering variables through the GUI a value is required, and the reduction will not proceed otherwise.
Change this so the entry system is more flexible. Ideally both the box can be left blank, or 'none' can be entered.

 - - - - 
Keywords: AUTOREDUCTION

**Comment by cyclohexanamine** [comment]
For future reference, the validation occurs in `run_variables.js`, `validateNotEmpty()`.
