### ISSUE TITLE
Improve autoreduce additional save directory functionality

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#123]
This issue was originally [TRAC 11433](http://trac.mantidproject.org/mantid/ticket/11433)

Currently when specifying an additional save location in the reduce.py script, it will blindly save to that exact location. Ideally it would save in an generic way similar to archive/ceph saving eg. '/userdirectory/data/inst$/rb$/run$' rather than just in the '/userdirectory/data/' directory. 

 - - - - 
Keywords: AUTOREDUCTION

**Comment by Anders-Markvardsen** [comment]
If a specific user request this we will open an issue for it
