### ISSUE TITLE
Explore and document how autoreduce updates the reduce.py/reduce_var.py script cache

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#124]
This issue was originally [TRAC 11434](http://trac.mantidproject.org/mantid/ticket/11434)

There have been some issues noticed with how the script files for autoreduce are loaded. For example, currently when adding new instrument variables you can only set the start run number to 1 more than the highest run job for that instrument. Additionally, when running run x with reduce.py, then attempting to run x-1 with a slightly different reduce.py script, it will use the original. This doesn't happen if running with run x+1, however.

Explore these issues and document why they happen. If trivial to fix, do so, otherwise think of potential solutions and discuss them.

 - - - - 
Keywords: AUTOREDUCTION

**Comment by Anders-Markvardsen** [comment]
Exploration finished. Will be fixed in #135
