### ISSUE TITLE
Implement a fall-back solution for when information not available from ICAT

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#128]
This issue was originally [TRAC 11517](http://trac.mantidproject.org/mantid/ticket/11517)

Implement a fall-back solution for when information from ICAT is not available. Currently autoreduction fails if ICAT information cannot be retrieved.

---

Keywords: AUTOREDUCTION

**Comment by Anders-Markvardsen** [comment]
Note where for whatever reason ICAT is not returned what is expected, ensure email notification is sent to isisreduce@stfc.ac.uk with a copy of query + unexpected response. Such information where relevant can then be emailed to isisdata@stfc.ac.uk , i.e. ICAT

**Comment by lottiegreenwood** [comment]
Covered via https://github.com/mantidproject/autoreduce/issues/324
