### ISSUE TITLE
Alternative mechanism for sending end of runs messages to autoreduce

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#129]
This issue was originally [TRAC 11518](http://trac.mantidproject.org/mantid/ticket/11518)

Code for this is used by a number of groups in the lab including Alex (and the powder diffraction scripts uses this).

In addition see below reply to Nick from Freddie about Knowing when runs ends:

as an alternative to using the “end of run” bat file (which we are happy for you to add something to), there is currently a file updated on the archive each time a run is ended. It is called “lastrun.txt” and is located in the “logs” area e.g.   \\isis\inst$\NDXMERLIN\Instrument\logs

The file contains:

    file_prefix  run_number  sav_file_count

If sav_file_count is 0  the the run has ended and you will have “file prefix””run_number”.nxs etc present on the archive

If sav_file_count is > 0 then this indicates that the run hasn’t ended yet, but an update/store has been used to create .n001 and .s001 etc files, the number given being the highest index of file currently used. So you could auto-reduce sav files too prior to run end if you wished.

I have a linux file watcher program using this mechanism that Pascal runs on some of his linux machines to automatically copy files across to them at run end, it just monitors the file modification date of lastrun.txt via a cifs mount of the archive and then reads its contents when the file date changes; it knows the last run it has, and then knowing the last run in the archive it can copy across any missing runs.

 - - - - 
Keywords: AUTOREDUCTION

**Comment by lottiegreenwood** [comment]
refs https://github.com/mantidproject/autoreduce/tree/129_EndofRun_Monitoring_Script

**Comment by DominicOram** [comment]
Code is now running as a service on the 'reduce' server, watching LET
