### ISSUE TITLE
Change how excitations reduced data is stored

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#134]
This issue was originally [TRAC 11702](http://trac.mantidproject.org/mantid/ticket/11702)

Currently data is stored in directory /instName/CYCLENAME/autoreduced/rbnumber/runnumber/results

The excitations group would rather have their data stored with all runs in the same rbnumber folder, so no runnumber or results folder.

Additionally they would like the relevant logs stored there.

 - - - - 
Keywords: AUTOREDUCTION

**Comment by Anders-Markvardsen** [comment]
Currently the reduction log file is stored as number.log where number is RB number this needs to be changed as part of this ticket. Here suggest changing this to RBxxRunXXX.log where xx is the RB number and XXX is the run number. The same apply to any *.err file saved.

This is a specific request from the excitation group. For any other instrument writting to CEPH save to /instName/.../rbnumber/runnumber

**Comment by Anders-Markvardsen** [comment]
Remove 'results' from all saved data makes sense
