### ISSUE TITLE
FunctionalID for autoreduce service

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#136]
This issue was originally [TRAC 11721](http://trac.mantidproject.org/mantid/ticket/11721)

Currently autoreduce exists only as a user within the autoreduce server. This causes problems with it not having the right permissions to save files on outside servers like the Ceph cluster. Obtain a functionalID for the autoreduce service and ensure that it is working correctly.

 - - - - 
Keywords: AUTOREDUCTION

**Comment by Anders-Markvardsen** [comment]
Function ID ISISautoreduce has been setup and is now been used
