### ISSUE TITLE
Set up NFS partition for autoreduce

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#137]
This issue was originally [TRAC 11876](http://trac.mantidproject.org/mantid/ticket/11876)

Currently autoreduce saves the end data for users to access in either the archive or ceph. It might be an idea to have an NFS directory of data also exposed in case of emergencies. 
Instructions on set up here: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/nfs-serverconfig.html

 - - - - 
Keywords: AUTOREDUCTION

**Comment by Anders-Markvardsen** [comment]
If this comes up for discussion again we will now ask it service desk to do this
