### ISSUE TITLE
Jobs sent in quick succession on the same data produce unexpected results

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#143]
This was first picked up when testing #13 

Unexpected behaviour occurs if one subprocess of PostProcessAdmin.py is running on the same data as another. At the moment this mostly shows itself as an Exception when trying to read the length of the error log as it has been deleted by the previous process. A quick fix would be to check whether the error log exists at this point but this does not solve the more general issue. To solve this some sort of lock may be required.

**Comment by DominicOram** [comment]
The issue picked up in #13 may actually be the one outlined in #146 but the behaviour of multiple runs on the same data should still be investigated

**Comment by Anders-Markvardsen** [comment]
@DominicOram Please provide a step by step example of how to reproduce this

**Comment by DominicOram** [comment]
To reproduce:

* Run a job on an instrument using a reduce script that will take some amount of time.
* Immediately run the same job, using the same data and reduced data directory.
* One of these jobs will fail as the error log could not be copied to the reduced data directory.

**Comment by cyclohexanamine** [comment]
The system currently seems to prevent this from happening by disallowing the creation of duplicate runs for as long as the pre-existing run's status is not complete or error. It will log an error such as `An invalid attempt to queue an existing reduction run was captured. Experiment: 1510188, Run Number: 75513, Run Version 0`.
