### ISSUE TITLE
Populate error log with errors from reduce.py

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#144]
Currently if an error occurs in reduce.py the error log saved to the archive/CEPH directory contains no information. It should instead be populated with the reduce.py exception. There may also be useful information in the Mantid logs that could be included.

**Comment by Anders-Markvardsen** [comment]
Currently we save a .err and a .log. Reassess if it make sense to return two outputs. This was setup before the webapp was developed. The .err was meant to only appear if an error was captured to the run, with a summary error message.

**Comment by Anders-Markvardsen** [comment]
For now keep both .err and .log. Where .err get what is returned to WebApp as a minimum, and .log gets the standard out but also ideally the mantid log output.

**Comment by DominicOram** [comment]
Redirecting output from C in python requires some subtlety. This blog post explains why and outlines some solutions. http://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/
