### ISSUE TITLE
Investigate scripts relationships in web database

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#145]
Previously runs were getting stuck in the 'Queued' message pool. This is due to the database that is used by both the website and queue_processor.py not containing correct information on the location of the reduction scripts. For now the information has been added through the web interface (to do this go to http://reduce.isis.cclrc.ac.uk/instrument/INST/variables/1/0/, where INST is the stalling instrument, reset the script to default and submit changes). This seems to fix the issue permanently but it may be useful for the system to look for the script itself if it cannot be found in the database.

**Comment by Anders-Markvardsen** [comment]
@DominicOram please provide a step by step example of how to get a message stuck in the 'Queued' message pool

**Comment by DominicOram** [comment]
To get a message stuck:
* Using the Django admin panel delete all the records in the 'Script Files' table of the SQL database behind the website
* Attempt to perform a run

This problem is similar to #135 and comes from the mechanics of the way the website stashes and loads scripts.

**Comment by Anders-Markvardsen** [comment]
This issue keep open but less high priority now that #135 has been fixed

**Comment by cyclohexanamine** [comment]
Now that `ScriptFile`s don't exist in the DB any more, this is irrelevant.
