### ISSUE TITLE
View WebApp without logging through users.facilities login

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#159]
Currently can only view reduce.isis.cclrc.ac.uk by logging in through https://users.facilities.rl.ac.uk/auth/?service=http://reduce.isis.cclrc.ac.uk&redirecturl=http://reduce.isis.cclrc.ac.uk/

Where this service is not available, have a fallback that allows reduce.isis.cclrc.ac.uk still to be viewed - even if this, for example, is initially just from the server the webapp is running on

**Comment by lottiegreenwood** [comment]
this has been fixed on the dev branch
