### ISSUE TITLE
upload manual job submission script that takes instrument name as input

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#161]
Add modified version of existing isis tricker script and call in manualJobSubmission.py.

Before uploading:

1) take out passwords
2) use a similar mechanism as is done in /scripts/EndOfRunMonitor/ISISendOfRunMonitor.py for generating the data path, i.e. assume the current cycle's "\logs\lastrun.txt" has the right format for constructing filename where the second number in that file is used ot determine the number of digits in the filename 
3) modify so input to this script is INSTNAME RUN_NUMBER_START RUN_NUMBER_END Y/N RBNUM CYCLE
4) set the queue priority to the lowest activemq value

@lottiegreenwood

**Comment by DominicOram** [comment]
Would it be useful to lookup RB numbers from the summary.txt file in the same way that the EndOfRun script does instead of asking the user for their RB number?

**Comment by Anders-Markvardsen** [comment]
That would be useful
