### ISSUE TITLE
Mantid log file have just disappeared. 

### ISSUE THREAD

**Issue by abuts** [mantidproject/autoreduce#170]
I have run reduction and reduction log files not there any more (neither output+err nor Mantid) 
Strange but clearly a bug. 

In addition to that, it seems something in the GUI generates multiple job submissions. Can not clearly identify what is that but certainly see much more jobs in the queue then I've consciously submitted.

**Comment by DominicOram** [comment]
What RB number were you using when you saw the multiple jobs? Could this be another case of #156?

**Comment by abuts** [comment]
See the reply on https://github.com/mantidproject/autoreduce/issues/156
