### ISSUE TITLE
Investigate Samba dependence

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#179]
We have seen some issues with the samba share recently. This is used by the queueProcessor on the reduce to pick up reduction scripts from autoreduce. Could it be possible to send the whole script in the activeMQ message instead and remove our samba dependency?

**Comment by DominicOram** [comment]
The biggest issue in doing this is would be a discussion on where in the process variables from reduce_vars.py are inserted into reduce.py. Currently this is done in PostProcessAdmin so both scripts will have to be sent through the message chain or the scripts will have to be combined earlier (potentially in queueProcessor). 

Other than that there seems to be no issue in the size of messages sent through ActiveMQ, especially as scripts are currently very small (<1MB). If scripts start to increase in size there are options that may help improve performance (http://activemq.apache.org/blob-messages.html)

**Comment by Anders-Markvardsen** [comment]
We today observed a problem with using samba again for transferring reduction scripts. In autoreudction.txt log this means messages of the type:

{{{
[25/Sep/2015 08:51:13] ERROR [django:34] Couldn't write temporary script - [Error 1326] The user name or password is incorrect: '\\\\autoreduce\\data\\'
[25/Sep/2015 08:51:13] ERROR [django:36] Error opening \\autoreduce\data\: The user name or password is incorrect
[25/Sep/2015 08:51:13] ERROR [django:61] UNCAUGHT ERROR: [Error 1326] The user name or password is incorrect: '\\\\autoreduce\\data\\'
}}}

**Comment by lottiegreenwood** [comment]
closed via https://github.com/mantidproject/autoreduce/issues/277
