### ISSUE TITLE
Investigate using script modification time

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#192]
At one point scripts were on the instrument had their modification times checked against those of the scripts in the database to reduce the number of times the scripts were loaded into the database. This functionality was removed in #191 as it was causing some errors in places when re-running scripts. This optimisation could be introduced at a later stage if required.

**Comment by cyclohexanamine** [comment]
At this point scripts are just loaded straight into the database without metadata for simplicity. I don't think there is any particular utility in loading scripts into the database less often.
