### ISSUE TITLE
Refactor run_variables.js

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#198]
Currently the run_variables script is used on three different pages (instrument_variables, submit_runs and run_variables). Some functionality is shared by all three pages .e.g. checking variables are valid. However, there are also a number of cases where the exact page has to be checked and specific actions performed. It will be easier to maintain if this script was broken up into separate scripts, a common one and a specific one for each page.

**Comment by cyclohexanamine** [comment]
There are only a few lines where this is the case, I don't think it would clarify much.
