### ISSUE TITLE
Bugfix: Help text on variables

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#202]
It appears that run variables only contain the help text from the reduce_vars.py script in some cases. It is not clear what the specific circumstances are under which this works. For an example that does not work see http://reduce.isis.cclrc.ac.uk/runs/26012/0/

**Comment by abuts** [comment]
not fixed.
Go to merlin, e.g. run 26028. No help strings there, though the reduction variables are correct and I had correct help strings when I replaced script and changed script variables to run then from 26027. 

I can bring help strings back by "Reset to current scripts and values" 
this makes vanadium run incorrect. 
When I change vanadium to correct value /archive/NDXMERLIN/Instrument/data/cycle_14_3/MER23684.raw and type "Rerun with new variables",
the help strings are not there any more.

**Comment by abuts** [comment]
From other side, next run (26029) looks fine....
do not know what to say. Please, resubmit the fix -- may be it has gone and old fail was doing something from cash. 
(I will retest)

**Comment by DominicOram** [comment]
This issue will be fixed for any runs going forward but may not be correct for rerunning old runs. If this is a major problem I can keep looking into it and apply the change retrospectively but this may be a lot of work. Is it required?

**Comment by abuts** [comment]
no -- it does not required -- I think if all following will work we fine. You will probably clear database anyway.

**Comment by DominicOram** [comment]
In that case I'll close the issue.
