### ISSUE TITLE
Automatically restart queueProcessor when new RB numbers to CEPH

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#221]
At present when new RB numbers are added to CEPH unless the the deamon for queueProcessor is restarted it will not know it has access to these RB folders and therefore can't write results to these.

During cycle new RB numbers may (but likely rarely) be added during update 12:30am and 12:30pm. 

It would be natural have restarts happen following these updates. If this was done as part of the RB number update then could limit restart to only when new RB are actually added. 

As part of this issue ensure that a queueProcessor is done safely and with e.g. causing active PostProcessAdmin jobs to stop or misfunction.

**Comment by cyclohexanamine** [comment]
I can confirm that this is still an issue. The user that the process is running as has access to the folders, but attempts to modify them results in `Error 13`. Restarting the queue processor fixes the problem, although I think that the system should be able to handle the changes without restarting. I'm not sure how it would be done.
