### ISSUE TITLE
Ensure that help text is correct

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#226]
The help text on the WebApp, both in the Help Pages and the popover text across the rest of the site, should be up to date, accurate and comprehensive.

**Comment by bence899** [comment]
In the help pages do the following:
* Provide contact info for the user office.
* Be more formal, using better words. E.g. once you are (part) of this team. Not (relationship).
* Provide a more specific title of an issue. E.g. when changing variables why is value X invalid for variable Y?
* When trying to type in something in the search bar, the pop up message can’t be read on a full 100% scale only at a 75% scale which is very inconvenient towards the user. 
* This help page could be developed even more to provide users a more convenient and clear source of help, by providing screenshots of how to carry out certain processes this question here is the perfect example to use.
