### ISSUE TITLE
Convert WISH Script

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#234]
Pascal has provided a reduction script which must be converted to properly work with autoreduction.

The script can be found at \\olympic\babylon5\Scratch\Anders\Pascal and requires a number of accompanying files which should be stored on Samba at \\autoreduce\InstrumentFiles\

**Comment by DominicOram** [comment]
This issue is complete but as no repo code has changed I see no point in creating a PR. 

To Test:
* Send a job on WISH and confirm that it completes and that data can be found in the output directory
* Download the script and run it on it's own, confirm that it runs and that data is in the specified directory

**Comment by Anders-Markvardsen** [comment]
Hi @DominicOram could you add directly to master a wish folder to https://github.com/mantidproject/autoreduce/tree/master/ReductionScripts/isis and upload your modified wish script and make reference to this issue? I will separate start to test this issue

**Comment by Anders-Markvardsen** [comment]
testing with re-run WISH 31422. It runs but get error:  Unable to copy to /instrument/WISH/CYCLE20151/RB1520384/autoreduced/ - could not create '/instrument/WISH/CYCLE20151/RB1520384': Permission denied - Hence issue with CEPH permissions - should be fixed now - try running it again. Worked as described
