### ISSUE TITLE
Adding Variables for Unscheduled RB numbers gives no error 

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#239]
When adding future variables by RB number only those RB numbers that are scheduled on the instrument are allowed. This is fine but the user is given no feedback if they enter an disallowed RB number. 

To replicate:
* Add new instrument variables by Experiment number
* Give an obviously bad experiment number (e.g. 100)
* Submit
* Confirm that the page is redirected, no experiment run numbers are shown and no errors are reported to the user

**Comment by DominicOram** [comment]
The variables are actually created, despite that the associated experiments are not scheduled. However, they do not appear in the list of upcoming variables and so no feedback is provided for the user.

**Comment by cyclohexanamine** [comment]
As of now the variables are created and scheduled without validating the RB# at all. I don't think it makes much sense to rely on ICAT to check that the experiments given are valid.
