### ISSUE TITLE
Scripts with no reduction variables cannot be run

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#241]
Some reduction scripts, e.g. the current WISH one, do not require any variables in reduce_vars. If a reduce_vars with empty variable dictionaries is given an error is seen on the WebApp. This should be fixed so that reductions without variables can still be run.

To reproduce:
* Edit a reduce_vars to be empty dictionaries
* Go to re-run a job
* Reset the job to the current script/values
* Submit the script and see an error

**Comment by DominicOram** [comment]
This bug will be complicated by the fact that links to scripts are stored as a property of each run variable, not each run and so a run with no variables will not have an associated script. It would make more sense to me for the WebApp database to be ordered with runs linked to scripts. @Anders-Markvardsen @MarcusNoble is there a reason for this organisation that I'm missing?

**Comment by lottiegreenwood** [comment]
closed in https://github.com/mantidproject/autoreduce/pull/289
