### ISSUE TITLE
Fix user permissions

### ISSUE THREAD

**Issue by DominicOram** [mantidproject/autoreduce#255]
In #207 a large number of security checks were removed in the WebApp. This needs to be reviewed as it may be that users can rerun runs that do not belong to them. To test this issue a test account that is not a superuser is required.

**Comment by cyclohexanamine** [comment]
The checks that were removed are necessary to stop users from seeing/rerunning runs and touching instruments that they shouldn't be able to. I've re-enabled them in [this branch](https://github.com/mantidproject/autoreduce/tree/255_user_permissions), and while the checks themselves work, it seems that for users, querying ICAT as a whole doesn't work. @lottiegreenwood, do you know how the ICAT is supposed to work, and who would have what information there?
