### ISSUE TITLE
Get HRPD script setup with new autoreduction

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#258]
The old HRPD scripts are located at https://github.com/mantidproject/autoreduce/tree/master/ReductionScripts/isis/hrpd

Replace/update these with scripts that work reduce.py and reduce_vars.py as shown with an example in https://github.com/mantidproject/autoreduce/tree/master/ReductionScripts/isis/DemoExample 

For production this script will then subsequently replace those in \isis\inst$\NDXHRPD\user\scripts\autoreduction

**Comment by lottiegreenwood** [comment]
Closed due to inactivity
