### ISSUE TITLE
When user specify nonsense addition save location

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#259]
If in a reduce.py if user returns an addition save location in the main() method the error you get from the web interface is 
```
 REDUCTION Error: 'data'
```
In the reduction output file RB#Script.out you get someone a bit better:
```
  File "/usr/bin/PostProcessAdmin.py", line 225, in reduce
    out_directories = reduce_script.main(input_file=str(self.data_file), output_dir=str(reduce_result_dir))
  File "/autoreducetmp/data/reduction_script_temp/scripts/c3a41006-f97b-4bc5-980d-61595c66bf6b/reduce.py", line 31, in mai
n
    additional_save_location = reduce(kwargs['data'], kwargs['output'])
KeyError: 'data'

```

Change the error message 'data' to something like (referring to the above example) 'Not recognised additional save location returned by main() method in reduce.py: reduce(kwargs['data'], kwargs['output'])'

**Comment by lottiegreenwood** [comment]
fixed in https://github.com/mantidproject/autoreduce/issues/271
