### ISSUE TITLE
Jobs sent in quick succession on different excitation data produce unexpected results

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#260]
Related issue is #143 

For example re-run MERLIN 28128-18147 and about every other run fails (using copy of reduction scripts in https://github.com/mantidproject/autoreduce/tree/master/ReductionScripts/isis/merlin )

The reason for this is that the excitation group writes the reduction results for different runs to the same folder, which for similar reason what is observed in #143 can cause unexpected failure when jobs run in quick succession. 

A fix to this could be to create the temporary folder names differently, i.e. the folders where the reduction happens. These don't need to have meaning full names. For instance in this case add run number would be enough, although that would not fix #143. But add data and time should fix both this issue and #143 for 99.9-100% (since at present activemq is feeding one at time hence there you should alway? be a time different). Or some/else better which cannot cause name clashes.

**Comment by lottiegreenwood** [comment]
fixed via https://github.com/mantidproject/autoreduce/pull/270
