### ISSUE TITLE
is_paused in autoreduce database deprecated

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#265]
within the Autoreduction database, there is both an is_active and is_paused. the is_paused appears to be used rarely within the codebase, and is superceded by is_active. Remove any queries using it, and replace them with is_active

**Comment by cyclohexanamine** [comment]
In fact the opposite is true; `is_paused` is more recent than `is_active` [(here)](https://github.com/mantidproject/autoreduce/commit/c9a7f190f27efd5da82a1ff5aa651d97d05a7f42), and postdates the migrations built [here](https://github.com/mantidproject/autoreduce/blob/master/WebApp/ISIS/autoreduce_webapp/reduction_variables/migrations/0001_initial.py). The setup instructions #267 include the line `python /var/www/autoreduce_webapp/manage.py makemigrations` which rebuilds the migrations to the current object models, so perhaps those migrations in the repo should be removed altogether.
