### ISSUE TITLE
Improve tracks_script

### ISSUE THREAD

**Issue by cyclohexanamine** [mantidproject/autoreduce#299]
Currently this setting for variables - intended to mean that the variable is always initialised to the value from the script on disk - is fairly inconsistently implemented. Mainly
* It's the default setting for new variables - it makes no sense to have that, because that implies any changes made will be thrown away.
* Editing variables with `tracks_script` set is allowed (and sometimes works) - they should always be fixed to their correct values.
* The variables are not always kept up to date with the script.

**Comment by lottiegreenwood** [comment]
closed via https://github.com/mantidproject/autoreduce/pull/302
