### ISSUE TITLE
Improve dev server

### ISSUE THREAD

**Issue by cyclohexanamine** [mantidproject/autoreduce#315]
The dev server doesn't work with production UOWS, and I didn't have much luck with the dev UOWS environment, so the authentication is bootstrapped with a few code changes. This makes it quite inconvenient to test/merge work. Possible solutions are getting the whole test environment, including UOWSdev and ICATdev, working, or implementing the code changes as a setting that can be changed easily.

The dev server right now is also out of date, so it should be brought up to date before working on it.

**Comment by cyclohexanamine** [comment]
The dev server is now up to date.

**Comment by lottiegreenwood** [comment]
dev server is up to date and set up
