### ISSUE TITLE
Multiple workers not currently possible

### ISSUE THREAD

**Issue by cyclohexanamine** [mantidproject/autoreduce#316]
The design of the system mostly allows for multiple worker nodes, thanks to the queue system. This would be useful for large workloads. But due to a few current design elements, this isn't feasible:
- The message queue is currently on the single worker node - #107
- The mechanism for not running multiple jobs of the same experiment at once - #270, #314 - assumes that only one worker is running.
- The mechanism for cancelling run retries (although not for retrying itself) - #280 - also assumes that only one worker is running.

**Comment by Anders-Markvardsen** [comment]
Has been fixed
