### ISSUE TITLE
Separate the actual reduction of runs from the copying across of runs

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#319]
Currently when a run is reduced, the effort taken to reduce it, and then the time taken to copy it from autoreducetmp folder to ceph or the archive is counted altogether. 
Considering that reducing data takes much more processing effort than copying it over, it makes sense to separate the two into different processes.
This would also make it simpler to keep runs that fail because file permissions are incorrect, instead of the actual reduction. We could store these 'failed' runs and then copy them over later when permissions had been correctly set up.

**Comment by lottiegreenwood** [comment]
This would also speed up processing runs from the same RB number, and reduce
`logger.info("Duplicate RB run #" + data["rb_number"] + ", waiting for the first to finish.")` logspam caused by fixing https://github.com/mantidproject/autoreduce/pull/270

**Comment by Anders-Markvardsen** [comment]
Archive for later
