### ISSUE TITLE
Information job submission script uses appears to have changed

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#328]
In last cycle the manual submission script would create data paths of the format:

Data: \\isis\inst$\NDXMARI\Instrument\data\cycle_16_4\\MAR21893.raw

but now I get:

Data: \isis\NDXMARI\Instrument\data\cycle_16_4\MARI21898.nxs

which is pointing to a non-existing file. I am guessing this is because controls have updated the format of the files we rely on for getting this information. People to speak to are Freddie and Dom. 

This highlight again something we already have an issue that we need a two tier subscription that both tries using controls information and that in ICAT. This also highlights that the job monitoring script does not check if the file path it put together doing exist - please fix this with this issue also.

**Comment by tg137** [comment]
This appears to be a problem with shortcodes and longcodes. At datafile level, instruments like MARI and MAPS have different file names to what the folder would suggest. This could be fixed with an XML file which indicates a mapping from short to long codes.

**Comment by Anders-Markvardsen** [comment]
I meant a pull request so we can test it first:-) I will do this now

**Comment by Anders-Markvardsen** [comment]
Tested with MARI 21839 which now works. @tg137 note that even though you corrected for accidently added the password it is now in the github history. If this happens accidently again revert back the commit rather than adding another on top. autoreduce is not externally visible, still this password needs to be changed - speak tomorrow
