### ISSUE TITLE
logging doesn't work as expected

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#329]
as I understand it, adding in 'logger.info(text)' to any python file in the autoreduce webapp frontend should mean the log is added to the main autoreduce.log . Logging only seems to work in queue_processor.py though.
(Currently calling methods from files that won't log within queueprocessor...)

**Comment by lottiegreenwood** [comment]
this might be related: https://www.caktusgroup.com/blog/2015/01/27/Django-Logging-Configuration-logging_config-default-settings-logger/

**Comment by tg137** [comment]
Will probably be fixed in #336

**Comment by lottiegreenwood** [comment]
![image](https://cloud.githubusercontent.com/assets/8983317/23652830/3bb1164e-0322-11e7-918f-d37fc9da9bc7.png)
