### ISSUE TITLE
There should be a nicer error message when you click "Re-run Past Jobs" on an instrument that doesn't have any jobs

### ISSUE THREAD

**Issue by jsws** [mantidproject/autoreduce#349]
At the moment when a user clicks "Re-Run Past Jobs" on an instrument that doesn't have any past jobs they get a stack trace back rather than a nice error message explaining what has gone wrong.

This should be caught and displayed as an informative message to the user.

**Comment by Anders-Markvardsen** [comment]
As discussed with @jsws close this issue
