### ISSUE TITLE
Add solution that avoids needing to change passwords in repository setting files

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/autoreduce#356]
Currently, passwords need to be changed in git repository file: https://github.com/mantidproject/autoreduce/blob/master/WebApp/ISIS/autoreduce_webapp/autoreduce_webapp/settings.py on both development and production, and it is too easy to accidentally commit such passwords to this externally visible repository.

Provide a solution to get around this.

**Comment by jsws** [comment]
I suggest we create a setting.py.example file that contains no sensitive information but provides a template for the settings.py. The settings.py should them be added to the .gitignore so it cannot be accidentally committed.
