### ISSUE TITLE
Make autoreduction more efficient through simultaneous reducing and sending of data on RHEL server

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#93]
This issue was originally [TRAC 11077](http://trac.mantidproject.org/mantid/ticket/11077)

Currently the autoreduction pipeline works such that when data is finished being autoreduced, and being sent to ICAT/Ceph cluster, it still counts as 1 process, and another data file that is queued cannot start until it has been sent, despite this not using as much server power. 

 - - - - 
Keywords: AUTOREDUCTION

**Comment by cyclohexanamine** [comment]
The queue processor no longer keeps count of a max number of processes, so this is not relevant.
