### ISSUE TITLE
Copying Merge file over at correct time

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/autoreduce#99]
This issue was originally [TRAC 11119](http://trac.mantidproject.org/mantid/ticket/11119)

Currently autoreduction copies Merge file over when copying newly reduced data to the archive. The merge file increases in size and causes the copying to be much slower. Instead, set it up so only at the end of a process, the merge file is copied across.

 - - - - 
Keywords: AUTOREDUCTION

**Comment by Anders-Markvardsen** [comment]
will make new issue where this may become relevant
